# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-03 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0003_auto_20170226_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalpermission',
            options={'managed': False, 'permissions': set([('app', 'Service desk right')])},
        ),
        migrations.AddField(
            model_name='journal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления'),
        ),
    ]
