# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-27 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0005_auto_20170403_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Заводской номер')),
                ('reg_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Рег. номер')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Грузоподъемность')),
                ('speed', models.PositiveIntegerField(blank=True, null=True, verbose_name='Скорость. м/с')),
                ('year_of_manufacture', models.PositiveSmallIntegerField(blank=True, default=2017, null=True, verbose_name='Год выпуска')),
                ('month_of_manufacture', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], default=8, null=True, verbose_name='Месяц выпуска')),
                ('year_of_start', models.PositiveSmallIntegerField(blank=True, default=2017, null=True, verbose_name='Год запуска')),
                ('month_of_start', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], default=8, null=True, verbose_name='Месяца запуска')),
                ('name_of_manufacture', models.CharField(blank=True, max_length=128, null=True, verbose_name='Изготовитель')),
                ('periodiki', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], null=True, verbose_name='Отметки переодики')),
                ('month_of_inspection', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], default=8, null=True, verbose_name='Месяц диагностики')),
                ('year_of_inspection', models.PositiveSmallIntegerField(blank=True, default=2017, null=True, verbose_name='Год диагностики')),
                ('payment', models.CharField(blank=True, max_length=128, null=True, verbose_name='Оплата')),
                ('prorab', models.CharField(blank=True, max_length=128, null=True, verbose_name='Прораб')),
                ('elmechanik', models.CharField(blank=True, max_length=128, null=True, verbose_name='Эл.Механик')),
                ('make', models.CharField(blank=True, max_length=128, null=True, verbose_name='Марка лифта')),
                ('st_upr', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ст.Упр.')),
                ('communication', models.CharField(blank=True, max_length=128, null=True, verbose_name='Связь')),
                ('lifterka', models.CharField(blank=True, max_length=128, null=True, verbose_name='Лифтерка')),
                ('schema', models.CharField(blank=True, max_length=128, null=True, verbose_name='Схема')),
                ('kanat', models.CharField(blank=True, max_length=128, null=True, verbose_name='Канаты')),
                ('kvh', models.CharField(blank=True, max_length=128, null=True, verbose_name='КВШ')),
                ('reductor', models.CharField(blank=True, max_length=128, null=True, verbose_name='Редуктор')),
                ('engine', models.CharField(blank=True, max_length=128, null=True, verbose_name='Двигатель')),
            ],
            options={
                'verbose_name_plural': 'Лифты',
                'verbose_name': 'Лифт',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Владелецы лифтов',
                'verbose_name': 'Владелец лифта',
            },
        ),
        migrations.AddField(
            model_name='elevator',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicedesk.Owner'),
        ),
    ]
