# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-08 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0007_auto_20171008_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='entrance',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Подъезд'),
        ),
        migrations.AddField(
            model_name='elevator',
            name='floors',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Этажей'),
        ),
    ]
